// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRRdPg6IVB1O-9tKC-Ap2JcLar-GZ45Y',
    appId: '1:136653308352:web:b8bcc8526c95a0736bc825',
    messagingSenderId: '136653308352',
    projectId: 'chatapp-236de',
    authDomain: 'chatapp-236de.firebaseapp.com',
    storageBucket: 'chatapp-236de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo2ERYZwxOmaMw46xmE15VNU8Vq5hnvwc',
    appId: '1:136653308352:android:30e40bce7e565f9a6bc825',
    messagingSenderId: '136653308352',
    projectId: 'chatapp-236de',
    storageBucket: 'chatapp-236de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLeEJ5Vua_mXjGBofVPbCEgVxVZ_JY5I4',
    appId: '1:136653308352:ios:261fed7c457c213a6bc825',
    messagingSenderId: '136653308352',
    projectId: 'chatapp-236de',
    storageBucket: 'chatapp-236de.appspot.com',
    iosBundleId: 'com.example.bomamessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLeEJ5Vua_mXjGBofVPbCEgVxVZ_JY5I4',
    appId: '1:136653308352:ios:a0eccac3bd58eb506bc825',
    messagingSenderId: '136653308352',
    projectId: 'chatapp-236de',
    storageBucket: 'chatapp-236de.appspot.com',
    iosBundleId: 'com.example.bomamessenger.RunnerTests',
  );
}
